"""
QBL Protocols — Quantum Communication & Computation Protocols

High-level protocol implementations that work across dimensions.
Each protocol is parameterized by d and leverages the core gate algebra.
"""

import numpy as np
from typing import Tuple, List, Optional
from qbl.core.gates import shift, clock, fourier, controlled_sum


def teleportation(d: int = 13) -> dict:
    """
    Qudit teleportation protocol specification.
    
    Protocol:
    1. Prepare Bell pair on (channel_a, channel_b): QFT ⊗ I then SUM
    2. Joint Bell measurement on (source, channel_a): SUM† then QFT†
    3. Measure both → outcomes (m1, m2) ∈ Z_d × Z_d
    4. Apply corrections: X^(-m2) Z^(m1) to channel_b
    
    Returns protocol specification dict.
    """
    return {
        'name': f'teleportation_d{d}',
        'dimension': d,
        'num_qudits': 3,  # source + channel_a + channel_b
        'steps': [
            {'action': 'prepare_bell', 'targets': [1, 2]},
            {'action': 'inverse_sum', 'targets': [0, 1]},
            {'action': 'inverse_fourier', 'targets': [0]},
            {'action': 'measure', 'targets': [0, 1], 'outcomes': 'm1, m2'},
            {'action': 'correct_shift', 'target': 2, 'amount': '-m2'},
            {'action': 'correct_phase', 'target': 2, 'amount': 'm1'},
        ],
        'fidelity': 1.0,  # Perfect in noiseless case
        'classical_communication': f'2 × log2({d}) bits',
        'entanglement_cost': f'1 Bell pair in C^{d}⊗C^{d}',
    }


def superdense_coding(d: int = 13) -> dict:
    """
    Qudit superdense coding protocol.
    
    Encode d² classical messages using 1 qudit transmission + 1 Bell pair.
    For d=13: encode 169 messages (vs 4 for qubits).
    """
    return {
        'name': f'superdense_d{d}',
        'dimension': d,
        'classical_capacity': d**2,
        'classical_bits': 2 * np.log2(d),
        'quantum_channel_uses': 1,
        'steps': [
            {'action': 'prepare_bell', 'targets': ['alice', 'bob']},
            {'action': 'encode', 'target': 'alice', 'message': '(a,b) ∈ Z_d × Z_d',
             'operation': 'X^a Z^b'},
            {'action': 'send', 'from': 'alice', 'to': 'bob'},
            {'action': 'bell_measure', 'targets': ['alice_qudit', 'bob_qudit']},
            {'action': 'decode', 'outcomes': '(a,b)'},
        ],
    }


def quantum_key_distribution(d: int = 13) -> dict:
    """
    BB84-analog QKD for dimension d.
    
    For d=13: key rate advantage of log2(13)/log2(2) ≈ 3.7x per symbol.
    Uses d+1 mutually unbiased bases (MUBs) for prime d.
    """
    num_mubs = d + 1  # Maximum for prime d
    return {
        'name': f'qkd_d{d}',
        'dimension': d,
        'num_bases': num_mubs,
        'bits_per_symbol': np.log2(d),
        'error_threshold': 1 / (d + 1),  # Tolerable error rate
        'advantage_over_qubits': np.log2(d),
        'steps': [
            {'action': 'alice_prepare', 'basis': f'random from {num_mubs} MUBs',
             'state': f'random from {d} levels'},
            {'action': 'transmit_qudit'},
            {'action': 'bob_measure', 'basis': f'random from {num_mubs} MUBs'},
            {'action': 'basis_reconciliation', 'classical_channel': True},
            {'action': 'error_estimation'},
            {'action': 'privacy_amplification'},
        ],
    }


def quantum_error_correction(d: int = 13, n: int = 5) -> dict:
    """
    Qudit stabilizer code specification [[n,1,t]]_d.
    
    For prime d: stabilizer group is generated by tensor products of
    Weyl operators D(a,b) = X^a Z^b.
    """
    t = (n - 1) // 2  # Correctable errors
    return {
        'name': f'stabilizer_code_d{d}_n{n}',
        'dimension': d,
        'physical_qudits': n,
        'logical_qudits': 1,
        'correctable_errors': t,
        'code_distance': 2 * t + 1,
        'stabilizer_group_order': d**(n - 1),
        'syndrome_alphabet': d,  # Each syndrome ∈ Z_d
        'steps': [
            {'action': 'encode', 'logical_state': '|ψ⟩_L',
             'output': f'{n}-qudit codeword'},
            {'action': 'syndrome_measure', 'generators': n - 1,
             'outcomes': f'({n-1}) values in Z_{d}'},
            {'action': 'decode_syndrome', 'method': 'lookup table or ML decoder'},
            {'action': 'apply_correction', 'operator': f'X^a Z^b on identified qudit'},
        ],
    }


def quantum_fourier_arithmetic(d: int = 13) -> dict:
    """
    Modular arithmetic circuits native to dimension d.
    
    For d=13 (prime): all arithmetic mod 13 is native.
    - Addition: SUM gate
    - Multiplication: modular multiply gate (for all a coprime to 13)
    - Exponentiation: repeated multiplication
    - Discrete log: QFT-based
    """
    coprimes = [a for a in range(1, d) if np.gcd(a, d) == 1]
    return {
        'name': f'arithmetic_d{d}',
        'dimension': d,
        'native_operations': {
            'addition': 'SUM gate (single two-qudit gate)',
            'subtraction': 'SUM† gate',
            'multiplication': f'MULT(a) for a ∈ {coprimes}',
            'inverse': f'MULT(a^{{-1}}) via Fermat little theorem',
            'exponentiation': 'Repeated squaring with MULT gates',
            'discrete_log': 'QFT on multiplicative group',
        },
        'group_structure': {
            'additive_group': f'Z_{d} (cyclic, order {d})',
            'multiplicative_group': f'Z_{d}* (cyclic, order {d-1})',
            'generators': [2],  # 2 is a primitive root mod 13
        },
    }
